#ifndef MEDI_CONFIG
#define MEDI_CONFIG

#include "sharedConfig.h"

#undef M_DEVICE_TYPE
#define M_DEVICE_TYPE DeviceType::Node

// Storage
#define M_DEVICE_STORAGE_DEFAULT_FILE_NAME "MEDI.00.BIN"
#define M_DEVICE_STORAGE_BUFFER_SIZE 128
#define M_DEVICE_STORAGE_SD_CARD_PIN 4
#define M_DEVICE_STORAGE_DISABLE_CS_PIN 10

// LoRa
#define M_DEVICE_LORA_NSS_PIN 8
#define M_DEVICE_LORA_NRESET_PIN 9
#define M_DEVICE_LORA_DIO0_PIN 2

// ECG
#define M_DEVICE_ECG_ANALOG_OUT A0
#define M_DEVICE_ECG_LOW_PLUS_IN 7
#define M_DEVICE_ECG_LOW_MINUS_IN 5

#define M_DEVICE_ECG_UPPER_THRESHOLD 518
#define M_DEVICE_ECG_LOWER_THRESHOLD 490

#define M_DEVICE_ECG_MINUTE_SECONDS 60
#define M_DEVICE_ECG_SECOND_MILLIS 1000

#define M_DEVICE_ECG_DEFAULT_READING_INTERVAL_MS 1
#define M_DEVICE_ECG_DEFAULT_CALCULATION_INTERVAL_MS 1000

#endif