#ifndef MEDI_SHARED_CONFIG
#define MEDI_SHARED_CONFIG

#include "messages/DeviceType.h"

#define M_DEVICE_NAME "MEDI"
#define M_DEVICE_FIRMWARE_VERSION_MAJOR 0
#define M_DEVICE_FIRMWARE_VERSION_MINOR 0
#define M_DEVICE_FIRMWARE_VERSION_PATCH 1
#define M_DEVICE_TYPE DeviceType::Unknown

// COM
#define M_DEVICE_COM_SERIAL_BAUDRATE 9600

// LoRa
#define M_DEVICE_LORA_DEFAULT_FREQ 868E6
#define M_DEVICE_LORA_NSS_PIN 8
#define M_DEVICE_LORA_NRESET_PIN 9
#define M_DEVICE_LORA_DIO0_PIN 2

#endif